
gateway {
  IKE-GW-FGT {
    protocol {
      ikev2 {
        ike-crypto-profile IKE-FGT-PA;
      }
      version ikev2;
    }
    local-address {
      interface ethernet1/1;
      ip 100.64.0.1/24;
    }
    peer-address {
      ip 100.64.0.2;
    }
    authentication {
      pre-shared-key {
        key -AQ==3ubINSR30pjL8XsaJHPpRxAosWQ=9Cbmgf587Y+P4vEguQl6y1HF2Y6C6PSYRkJZVAJc4Rc=;
      }
    }
  }
  IKE-GW-FGT2 {
    protocol {
      ikev2 {
        ike-crypto-profile IKE-FGT-PA;
      }
      version ikev2;
    }
    local-address {
      interface ethernet1/3;
      ip 100.100.0.1/24;
    }
    peer-address {
      ip 100.100.0.2;
    }
    authentication {
      pre-shared-key {
        key -AQ==3ubINSR30pjL8XsaJHPpRxAosWQ=9Cbmgf587Y+P4vEguQl6y1HF2Y6C6PSYRkJZVAJc4Rc=;
      }
    }
  }
}
