
ipsec {
  VPN-FGT-PA {
    auto-key {
      ike-gateway {
        IKE-GW-FGT;
      }
      ipsec-crypto-profile IPSEC-FGT-PA;
    }
    tunnel-interface tunnel.1;
  }
  VPN2-FGT-PA {
    auto-key {
      ike-gateway {
        IKE-GW-FGT2;
      }
      ipsec-crypto-profile IPSEC-FGT-PA;
    }
    tunnel-interface tunnel.2;
  }
}
