
tunnel {
  units {
    tunnel.1 {
      ip {
        169.255.1.1/30;
      }
      interface-management-profile TUNNEL-MGMT;
    }
    tunnel.2 {
      ip {
        169.255.1.5/30;
      }
      interface-management-profile TUNNEL-MGMT;
    }
  }
}
