
virtual-router {
  default {
    protocol {
      bgp {
        enable yes;
        dampening-profile {
          default {
            cutoff 1.25;
            reuse 0.5;
            max-hold-time 900;
            decay-half-life-reachable 300;
            decay-half-life-unreachable 900;
            enable yes;
          }
        }
        local-as 65001;
        router-id 10.255.255.254;
        peer-group {
          IBGP-SDWAN {
            type {
              ibgp;
            }
            peer {
              FGT-SITE {
                local-address {
                  interface tunnel.1;
                  ip 169.255.1.1/30;
                }
                peer-address {
                  ip 169.255.1.2;
                }
              }
              FGT-SITE-VPN2 {
                local-address {
                  interface tunnel.2;
                  ip 169.255.1.5/30;
                }
                peer-address {
                  ip 169.255.1.6;
                }
              }
            }
          }
        }
        install-route yes;
        redist-rules {
          REDIST-DC {
            address-family-identifier ipv4;
            enable yes;
          }
        }
        policy {
          import {
            rules {
              IMP-COMM-VPN1 {
                enable yes;
                used-by IBGP-SDWAN;
                match {
                  community {
                    regex ^65001:1$;
                  }
                }
                action {
                  allow {
                    update {
                      local-preference 200;
                    }
                  }
                }
              }
              IMP-COMM-VPN2 {
                enable yes;
                used-by IBGP-SDWAN;
                match {
                  community {
                    regex ^65001:2$;
                  }
                }
                action {
                  allow {
                    update {
                      local-preference 150;
                    }
                  }
                }
              }
              IMP-COMM-DEGRADED {
                enable yes;
                used-by IBGP-SDWAN;
                match {
                  community {
                    regex ^65001:11$;
                  }
                }
                action {
                  allow {
                    update {
                      local-preference 50;
                    }
                  }
                }
              }
            }
          }
        }
      }
      redist-profile {
        REDIST-DC {
          priority 10;
          filter {
            type connect;
            destination 10.255.255.0/24;
          }
          action {
            redist;
          }
        }
      }
    }
    interface [ ethernet1/1 ethernet1/2 tunnel.1 ethernet1/3 tunnel.2];
  }
}
