config firewall address
    edit "none"
        set uuid 94b7ffbe-9657-51f1-4cee-b4493e3175cb
        set subnet 0.0.0.0 255.255.255.255
    next
    edit "login.microsoftonline.com"
        set uuid 94b807de-9657-51f1-2f82-db480d8ec5c1
        set type fqdn
        set fqdn "login.microsoftonline.com"
    next
    edit "login.microsoft.com"
        set uuid 94b80e14-9657-51f1-8ab7-790d9186c466
        set type fqdn
        set fqdn "login.microsoft.com"
    next
    edit "login.windows.net"
        set uuid 94b81170-9657-51f1-e4eb-edd9d2ba8c8a
        set type fqdn
        set fqdn "login.windows.net"
    next
    edit "gmail.com"
        set uuid 94b814b8-9657-51f1-acb4-fafa0cc1722f
        set type fqdn
        set fqdn "gmail.com"
    next
    edit "wildcard.google.com"
        set uuid 94b817f6-9657-51f1-fc8a-4bc65b353aaf
        set type fqdn
        set fqdn "*.google.com"
    next
    edit "wildcard.dropbox.com"
        set uuid 94b81b0c-9657-51f1-d96c-3399f800a18b
        set type fqdn
        set fqdn "*.dropbox.com"
    next
    edit "all"
        set uuid 9580cf0c-9657-51f1-61f0-0c4b1b0e7784
    next
    edit "FIREWALL_AUTH_PORTAL_ADDRESS"
        set uuid 9580d0ba-9657-51f1-c7f1-6415b77f4b46
    next
    edit "FABRIC_DEVICE"
        set uuid 9580d1fa-9657-51f1-f35a-0cd6cb8ebee2
        set comment "IPv4 addresses of Fabric Devices."
    next
    edit "SSLVPN_TUNNEL_ADDR1"
        set uuid 95815166-9657-51f1-717a-bb893ccfba05
        set type iprange
        set start-ip 10.212.134.200
        set end-ip 10.212.134.210
    next
    edit "BRANCH-LAN"
        set uuid 19ae16e6-96f7-51f1-46c3-bc69854cdb6a
        set subnet 10.0.0.0 255.255.255.0
    next
    edit "DC-LAN"
        set uuid 19b93cec-96f7-51f1-f4fa-a17f7683c920
        set subnet 10.255.255.0 255.255.255.0
    next
    edit "DC-SERVER-1"
        set uuid 19c32f22-96f7-51f1-2287-e8a87f9e634e
        set subnet 10.255.255.1 255.255.255.255
    next
end

