config firewall addrgrp
    edit "G Suite"
        set uuid 94b81ea4-9657-51f1-02c3-fd6d7ec958d4
        set member "gmail.com" "wildcard.google.com"
    next
    edit "Microsoft Office 365"
        set uuid 94b823cc-9657-51f1-9f01-a600101dfd2d
        set member "login.microsoftonline.com" "login.microsoft.com" "login.windows.net"
    next
end

