config firewall policy
    edit 1
        set name "BRANCH-LAN-to-VPN-DC"
        set uuid 2e89d5ba-9679-51f1-b173-e421da43f793
        set srcintf "port4"
        set dstintf "VPN-DC"
        set action accept
        set srcaddr "BRANCH-LAN"
        set dstaddr "DC-SERVER-1"
        set schedule "always"
        set service "SERVICES-DC"
        set logtraffic all
    next
    edit 2
        set name "VPN-DC-to-BRANCH-LAN"
        set uuid 2ea8bf5c-9679-51f1-3cb7-3eb37099d33a
        set srcintf "VPN-DC"
        set dstintf "port4"
        set action accept
        set srcaddr "DC-LAN"
        set dstaddr "BRANCH-LAN"
        set schedule "always"
        set service "SERVICES-MGMT"
        set logtraffic all
    next
    edit 3
        set name "DC-to-FG-MGMT"
        set uuid 667cc264-9702-51f1-70c0-3f3601a495c4
        set srcintf "VPN-DC"
        set dstintf "LO-MGMT"
        set action accept
        set srcaddr "DC-SERVER-1"
        set dstaddr "all"
        set schedule "always"
        set service "SERVICES-MGMT"
        set logtraffic all
    next
end

