config vpn ipsec phase1-interface
    edit "VPN-PA-DC"
        set interface "port2"
        set ike-version 2
        set keylife 28800
        set peertype any
        set net-device disable
        set proposal des-sha256
        set dhgrp 14
        set remote-gw 100.64.0.1
        set psksecret ENC 7RLgkGPnoVasaossRHgRJh9WGbYWb6x7lRaJwDBOzV9Hel9XsLu+o2EdcayODK/yhnAzrPPaHC/4glJyL/kIiQYvSYj+au2QIkMxjoxo8la3pcT3EC9A21EyH1WAWe1GGmv8YYzhiG+ORiK8BDAQLMTHkk6tCLjlEv9tYAdtCjP5X0NbJhMAeSN1ss2VOhdPROoL6A==
    next
    edit "VPN2-PA-DC"
        set interface "port3"
        set ike-version 2
        set keylife 28800
        set peertype any
        set net-device disable
        set proposal des-sha256
        set dhgrp 14
        set remote-gw 100.100.0.1
        set psksecret ENC HCLhofs+fKEr88yEbo/15BegvEs3+aLt2UAKePi7HDa2zWWStrfEf1g5oNn6w19na2GYI/vgxNC4NRIiMYgVqvrJeI2X48ECAmZmKR3zgq9d0o+S/qSHTHAiZjYWZNFJfmMikAQrzAWHg/5ud9uau1mSvN8lpSv9FNVVolybkZWZtMHA6NxkPg45WAUiG9eLSfjosw==
    next
end

