config vpn ipsec phase2-interface
    edit "VPN-PA-DC-P2"
        set phase1name "VPN-PA-DC"
        set proposal des-sha256
        set dhgrp 14
        set keylifeseconds 3600
    next
    edit "VPN2-PA-DC-P2"
        set phase1name "VPN2-PA-DC"
        set proposal des-sha256
        set dhgrp 14
        set keylifeseconds 3600
    next
end

