config router bgp
    set as 65001
    set router-id 10.0.0.254
    set ibgp-multipath enable
    config neighbor
        edit "169.255.1.1"
            set advertisement-interval 1
            set remote-as 65001
            set route-map-out "RM-OUT-VPN1"
            set route-map-out-preferable "RM-OUT-VPN1-PREF"
        next
        edit "169.255.1.5"
            set advertisement-interval 1
            set remote-as 65001
            set route-map-out "RM-OUT-VPN2"
            set route-map-out-preferable "RM-OUT-VPN2-PREF"
        next
    end
    config network
        edit 1
            set prefix 10.0.0.0 255.255.255.0
        next
        edit 2
            set prefix 172.31.255.1 255.255.255.255
        next
    end
    config redistribute "connected"
    end
    config redistribute "rip"
    end
    config redistribute "ospf"
    end
    config redistribute "static"
    end
    config redistribute "isis"
    end
    config redistribute6 "connected"
    end
    config redistribute6 "rip"
    end
    config redistribute6 "ospf"
    end
    config redistribute6 "static"
    end
    config redistribute6 "isis"
    end
end

