config router community-list
    edit "COMM-VPN1-PREFER"
        config rule
            edit 1
                set action permit
                set match "65001:1"
            next
        end
    next
    edit "COMM-VPN2-PREFER"
        config rule
            edit 1
                set action permit
                set match "65001:2"
            next
        end
    next
    edit "COMM-VPN1-DEGRADED"
        config rule
            edit 1
                set action permit
                set match "65001:11"
            next
        end
    next
    edit "COMM-VPN2-DEGRADED"
        config rule
            edit 1
                set action permit
                set match "65001:12"
            next
        end
    next
end

