config router route-map
    edit "RM-OUT-VPN1"
        config rule
            edit 1
                set set-community "65001:11"
            next
        end
    next
    edit "RM-OUT-VPN1-PREF"
        config rule
            edit 1
                set set-community "65001:1"
            next
        end
    next
    edit "RM-OUT-VPN2"
        config rule
            edit 1
                set set-community "65001:11"
            next
        end
    next
    edit "RM-OUT-VPN2-PREF"
        config rule
            edit 1
                set set-community "65001:2"
            next
        end
    next
end

