config system sdwan
    set status enable

    config zone
        edit "virtual-wan-link"
        next

        edit "VPN-DC"
        next

        edit "WAN-INTERNET"
        next
    end

    config members
        edit 1
            set interface "port2"
            set zone "WAN-INTERNET"
            set gateway 100.64.0.1
        next

        edit 2
            set interface "port3"
            set zone "WAN-INTERNET"
            set gateway 100.100.0.1
        next

        edit 3
            set interface "VPN-PA-DC"
            set zone "VPN-DC"
        next

        edit 4
            set interface "VPN2-PA-DC"
            set zone "VPN-DC"
        next
    end

    config health-check
        edit "SLA_DC"
            set server "10.255.255.1"
            set interval 1000
            set probe-timeout 250
            set failtime 2
            set recoverytime 10
            set members 3 4

            config sla
                edit 1
                    set latency-threshold 100
                    set jitter-threshold 20
                    set packetloss-threshold 5
                next
            end
        next

        edit "SLA_INTERNET"
            set server "8.8.8.8"
            set interval 1000
            set probe-timeout 500
            set failtime 3
            set recoverytime 3
            set members 1 2

            config sla
                edit 1
                    set latency-threshold 150
                    set jitter-threshold 30
                    set packetloss-threshold 5
                next
            end
        next
    end

    config neighbor
        edit "169.255.1.1"
            set member 3
            set health-check "SLA_DC"
            set sla-id 1
        next

        edit "169.255.1.5"
            set member 4
            set health-check "SLA_DC"
            set sla-id 1
        next
    end

    config service
        edit 1
            set name "TO-DC"
            set mode sla
            set minimum-sla-meet-members 1
            set dst "NET-DC"
            set src "all"

            config sla
                edit "SLA_DC"
                    set id 1
                next
            end

            set priority-members 3 4
            set tie-break cfg-order
        next

        edit 2
            set name "TO-INTERNET"
            set mode sla
            set dst "all"
            set src "all"

            config sla
                edit "SLA_INTERNET"
                    set id 1
                next
            end

            set priority-members 1 2
            set tie-break cfg-order
        next
    end
end
